### ISSUE TITLE
No mention of connect() in README

### ISSUE THREAD

**Issue by dcelasun** [elbart/node-memcache#13]
I had something like this in my code:

``` js
var memcache = require('node-memcache').Client,
       cache = new memcache();

cache.host = '192.168.1.1';
cache.port = 8080;

```

The README suggests I should now be able to call

``` js
cache.get()
```

which is not true. I had to do

``` js
cache.connect()
```

before I could access any objects. You should probably mention this somewhere in README.

**Comment by elbart** [comment]
thanks for the hint... I adjusted that

**Comment by dcelasun** [comment]
Wow, that was fast. Thanks!

**Comment by elbart** [comment]
thanks to the online editor :)
