### ISSUE TITLE
How to get unique token (for cas) from get call?

### ISSUE THREAD

**Issue by jstockdale** [elbart/node-memcache#15]
Traditionally (ie. in php-land) the cas token is returned as an optional parameter passed by reference to the get call. With this library, how is one supposed to retrieve the cas token with the get() call for a given key?

Thanks!

**Comment by elbart** [comment]
I'm sorry but I have to say that CAS is not supported yet... 

If I would build it, I would add the token as additional parameter to the callback.

**Comment by jstockdale** [comment]
Cool. Thanks!
