### ISSUE TITLE
Set/get are not working with UTF-8 values

### ISSUE THREAD

**Issue by alexei-lexx** [elbart/node-memcache#3]
just try commands
set key1 привет
get key1
which contains or returns Russian chars.

How to fix.
1. In Client.prototype.store, line 113 need to calculate bytes, not chars in string

var tml_buf = new Buffer(value);
var value_len = tml_buf.length || 0;
1. In Client.prototype.handle_get, line 247 add one more case

if (buffer.indexOf('END') == 0)  ...
else if (buffer.indexOf('VALUE') == 0) {
      first_line_len = buffer.indexOf(crlf) + crlf_len;
      var end_indicator_start = buffer.indexOf('END');
      result_len = end_indicator_start - first_line_len - crlf_len;
      result_value = buffer.substr(first_line_len, result_len);
      return [result_value, first_line_len + parseInt(result_len, 10) + crlf_len + end_indicator_len + crlf_len]
    }
    else ...

Regards, Alexei.

**Comment by elbart** [comment]
Hi Alexei,

thanks for the advice and sorry for being such non responsive over the last days. I hope I'll find some time during the next days to fix that problem.

Best regards,

Tim

**Comment by elbart** [comment]
Very late, but done today. Thx again ;)

Best regards.

Tim
