### ISSUE TITLE
Storing integers

### ISSUE THREAD

**Issue by Emmerman** [elbart/node-memcache#6]
client.set('key', 123); will not work because 
    var tml_buf = new Buffer(value);
creates buffer with 123 bytes length (http://nodejs.org/docs/v0.4.3/api/buffers.html#new_Buffer)

I think "var tml_buf = new Buffer(value.toString());" can help.

**Comment by elbart** [comment]
Thanks Emmerman for this report. 

wrote a simple test and fixed as you suggested.

Best Regards.

Tim
